name: Opus check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt install -y build-essential cmake gcc zlib1g-dev libgmp-dev libgtest-dev
      - run: mkdir build
      - run: ./test.sh
